### ISSUE TITLE
关于vio_loop.csv文件中闭环帧数量的问题

### ISSUE THREAD

**Issue by Shane922** [ccy89/VINS-Fusion-Comment#1]
你好，我在开启回环检测节点后，在生成的vio_loop.csv文件中发现其中总行数小于vio.csv中的行数（从vio.csv的时间戳来看，是每一个相机帧0.05s都有一个位姿值，而vio_loop.csv中则是随机间隔多帧），是不是其中只有关键帧？我考虑过后续处理时将vio中某一时间戳对应的pose和四元数替换为对应vio_loop中同时间戳的值，但是考虑还是直接能输出更为合适，请问你有什么解决的办法吗？github联系不便，方便的话可以加我qq讨论：1711491627，谢谢！

**Comment by ccy89** [comment]
vio_loop.csv 只存储关键帧的位姿
你后面的目的我不是很理解，为什么不是直接基于关键帧位姿做后续处理，你是希望使用所有帧，而不仅仅只是关键帧吗
